### ISSUE TITLE
cronjob is not enabled by default for can setup

### ISSUE THREAD

**Issue by padhupradheep** [neobotix/robot-setup-tool#38] opened 2023-06-12 09:37 UTC
https://github.com/neobotix/robot-setup-tool/blob/03cc7d62afe38aa239c629d08907de3562d22156/debian/neobotix-tools/DEBIAN/postinst#L32

Found issue in Ubuntu 22.04

CC: @neopar

**Comment by neopar** [comment] 2023-08-17 17:45
Duplicate of  #36

**Closed as completed by neopar** 2023-08-17 17:45 UTC
Labels: investigate
